server/monitoring/urls.py
from django.urls import path

from monitoring.views import AddLogView

urlpatterns = [
    path('add/', AddLogView.as_view())
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

from monitoring.views import EventsDashboardAdminView

urlpatterns = [
    path('admin/dashboard/', admin.site.admin_view(EventsDashboardAdminView.as_view())),
    path('admin/', admin.site.urls),
    path('monitoring/', include('monitoring.urls'))
]

server/monitoring/models.py
from django.db import models


class UserPC(models.Model):
    last_active_at = models.DateTimeField('Дата и время последней активности')
    is_compromised = models.BooleanField('Бали ли машина скомпрометирована', default=False)
    name = models.CharField(verbose_name='Имя машины', max_length=255)

    def __str__(self):
        return self.name


class LogType(models.Model):
    key = models.CharField('Ключ', max_length=255)

    def __str__(self):
        return self.key


class PCLogItem(models.Model):
    device = models.ForeignKey(UserPC, on_delete=models.CASCADE, verbose_name='Компьютер')
    created_at = models.DateTimeField('Дата создания записи', auto_now_add=True)
    remote_registered_at = models.DateTimeField('Дата/время регистрации на удаленном компьютере')
    log_type = models.ForeignKey(LogType, on_delete=models.CASCADE, verbose_name='Тип')
    text = models.TextField('Текст записи')

    def __str__(self):
        return f"{self.device.name} - {self.log_type.key} - {self.text[:250]}"


class SecurityEvent(models.Model):
    INFO = 0
    WARNING = 1
    CRITICAL = 2

    LEVEL_CHOICES = (
        (INFO, 'Информация'),
        (WARNING, 'Внимание'),
        (CRITICAL, 'Угроза')
    )

    level = models.PositiveSmallIntegerField(verbose_name='Уровень угрозы', choices=LEVEL_CHOICES)
    is_active = models.BooleanField(verbose_name='Активно ли?')
    records = models.ManyToManyField(PCLogItem, verbose_name='Записи логов')
    name = models.CharField('Короткое название', max_length=255)
    info = models.TextField('Описание события')
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)

    def __str__(self):
        return self.name

server/monitoring/views.py
#
# curl -H "Content-Type: application/json" -X POST --data '{"name": "home-desktop","logs":{"auth": ["Apr 10 18:16:38 vmax-VirtualBox udisksd[538]: udisks daemon", "Apr 10 21:17:00 vmax-VirtualBox sshd[3686]: pam_unix(sshd:auth): "]}}' localhost:8000/monitoring/add/
import json
import re
from datetime import datetime, timedelta

from django.db.models import Count
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import TemplateView

from analytics.cases.insert_cd import InsertCDAnalytics
from analytics.cases.port_scanning import PortScanningAnalytic
from analytics.cases.ssh_brutforce import SSHBrutforceAnalytics
from monitoring.models import UserPC, LogType, PCLogItem, SecurityEvent

LOG_TIME_PATTERN = re.compile(r'^([a-zA-Z]+) ([0-9]+) ([0-9:]+) ([\s\S]+)')


class AddLogView(View):

    def post(self, request, *args, **kwargs):
        """
        {"name":"имя компютера",
        "logs": {
                "log-key": ["records",...]
            }
        """
        today = datetime.now()
        data = json.loads(request.body.decode('utf-8'))

        name = data.get('name')
        user_pc = get_object_or_404(UserPC, name=name)
        logs = data.get('logs')
        for log_name in logs.keys():
            log_type = get_object_or_404(LogType, key=log_name)
            for row in logs[log_name]:
                if not row:
                    continue
                row_items = LOG_TIME_PATTERN.findall(row)[0]
                date_of_row = datetime.strptime(f'{row_items[1]}-{row_items[0]}-{today.year} {row_items[2]}',
                                                '%d-%b-%Y %H:%M:%S')
                row_body = row_items[3]
                row_in_db, _ = PCLogItem.objects.get_or_create(
                    remote_registered_at=date_of_row,
                    text=row_body,
                    log_type=log_type,
                    device=user_pc
                )
        PortScanningAnalytic().run()
        InsertCDAnalytics().run()
        SSHBrutforceAnalytics().run()
        return HttpResponse('ok')


class EventsDashboardAdminView(TemplateView):
    template_name = 'events_dashboard.html'

    def events_grouped_by_day(self):
        return SecurityEvent.objects.extra(select={'day': 'date( created_at )'}).values('day') \
            .annotate(available=Count('created_at'))

    def events_by_level(self):
        return SecurityEvent.objects.values('level').annotate(count=Count('id')).order_by('level')

    def logs_by_type_and_day(self):
        start_date = datetime.now() - timedelta(days=7)
        return PCLogItem.objects \
            .filter(created_at__gte=start_date) \
            .extra(select={'day': 'date( created_at )'}) \
            .values('day', 'log_type__key') \
            .annotate(available=Count('id')) \
            .order_by('day')

    def format_logs(self, name, date_mask, logs):
        filtered_items = [i for i in logs if name == i['log_type__key']]
        print(filtered_items)
        result = []
        for day in date_mask:
            cnt = next((i['available'] for i in filtered_items if i['day'] == day), 0)
            result.append(cnt)
        return result

    def get_context_data(self, **kwargs):
        ctx = super(EventsDashboardAdminView, self).get_context_data(**kwargs)
        events_per_day = self.events_grouped_by_day()
        events_by_level = self.events_by_level()
        security_events_level_choices = dict(SecurityEvent.LEVEL_CHOICES)
        logs = sorted(self.logs_by_type_and_day(), key=lambda i: i['day'])
        print(logs)
        logs_days = sorted(list({i['day'] for i in logs}))
        ctx['ALL_EVENTS_DAYS'] = json.dumps([i['day'] for i in events_per_day])
        ctx['ALL_EVENTS_VALUES'] = json.dumps([i['available'] for i in events_per_day])
        ctx['ALL_EVENTS_BY_TYPE_NAMES'] = json.dumps(
            [security_events_level_choices[i['level']] for i in events_by_level])
        ctx['ALL_EVENTS_BY_TYPE_VALUES'] = json.dumps([i['count'] for i in events_by_level])
        ctx['ALL_LOGS_DAYS'] = json.dumps(logs_days)
        ctx['ALL_LOGS_AUTH'] = self.format_logs('auth', logs_days, logs)
        ctx['ALL_LOGS_CD_ROM'] = self.format_logs('cd_rom', logs_days, logs)
        ctx['ALL_LOGS_USB_STORAGE'] = self.format_logs('usb_storage', logs_days, logs)
        ctx['ALL_LOGS_NETWORK'] = self.format_logs('network', logs_days, logs)
        ctx['EVENTS'] = SecurityEvent.objects.filter(is_active=True).order_by('-created_at')
        return ctx

server/monitoring/templates/events_dashboard.html
{% extends "admin/base_site.html" %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
    <style>
    tr:nth-child(2n){
        background: rgba(154, 207, 234, 0.57);
    }
    </style>
{% endblock %}

{% block content %}
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>
                        Дашборд
                    </h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <canvas id="allLogs"></canvas>
                </div>
                <div class="col-md-4">
                    <canvas id="eventsPerLevel"></canvas>
                </div>
                <div class="col-md-4">
                    <canvas id="eventsPerDay"></canvas>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h2>Активные события</h2>
                </div>
                <div class="col-md-12">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Дата</th>
                            <th scope="col">Уровень</th>
                            <th scope="col">Название</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for row in EVENTS %}
                            <tr>
                                <th scope="row">{{ row.id }}</th>
                                <td>{{ row.created_at }}</td>
                                <td>{{ row.get_level_display }}</td>
                                <td>{{ row.name }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <script src="{% static 'js/chart.js' %}"></script>
    <script>


        const labels2 = {{ALL_LOGS_DAYS|safe}};
        const data2 = {
            labels: labels2,
            datasets: [
                {
                    label: 'Auth',
                    data: {{ ALL_LOGS_AUTH| safe }},
                    backgroundColor: 'blue',
                },
                {
                    label: 'Cd rom',
                    data: {{ ALL_LOGS_CD_ROM| safe }},
                    backgroundColor: 'red',
                },
                {
                    label: 'USB storage',
                    data: {{ ALL_LOGS_USB_STORAGE| safe }},
                    backgroundColor: 'green',
                },
                {
                    label: 'Network',
                    data: {{ ALL_LOGS_NETWORK| safe }},
                    backgroundColor: 'orange',
                },
            ]
        };
        const config2 = {
            type: 'bar',
            data: data2,
            options: {
                plugins: {
                    title: {
                        display: true,
                        text: 'Сбор логов в день по типам'
                    },
                },
                responsive: true,
                scales: {
                    x: {
                        stacked: true,
                    },
                    y: {
                        stacked: true
                    }
                }
            }
        };
        var allLogs = new Chart(
            document.getElementById('allLogs'),
            config2
        );
        const data1 = {
            labels: {{ ALL_EVENTS_BY_TYPE_NAMES|safe }},
            datasets: [
                {
                    label: 'Dataset 1',
                    data: {{ ALL_EVENTS_BY_TYPE_VALUES|safe }},
                    backgroundColor: Object.values(['MediumSeaGreen', 'Goldenrod', 'OrangeRed',]),
                }
            ]
        };
        const config1 = {
            type: 'pie',
            data: data1,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'События по типам'
                    }
                }
            },
        };
        var eventsPerLevel = new Chart(
            document.getElementById('eventsPerLevel'),
            config1
        );


        const labels = {{ ALL_EVENTS_DAYS|safe }};
        const data = {
            labels: labels,
            datasets: [{
                label: 'Количество событий безопасности за неделю',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: {{ ALL_EVENTS_VALUES|safe }},
            }]
        };
        const config = {
            type: 'line',
            data,
            options: {}
        };
        // === include 'setup' then 'config' above ===


        var eventsPerDay = new Chart(
            document.getElementById('eventsPerDay'),
            config
        );
    </script>
{% endblock %}